<?php

declare(strict_types=1);

use GGermanBoldyrev\SchemaFile\Renderer\SchemaRenderer;
use GGermanBoldyrev\SchemaFile\Schema\Column;
use GGermanBoldyrev\SchemaFile\Schema\Expression;
use GGermanBoldyrev\SchemaFile\Schema\ForeignKey;
use GGermanBoldyrev\SchemaFile\Schema\Index;
use GGermanBoldyrev\SchemaFile\Schema\IndexType;
use GGermanBoldyrev\SchemaFile\Schema\Table;

function render(Table ...$tables): string
{
    return (new SchemaRenderer)->render($tables);
}

/**
 * The lines inside the first Schema::create() / Schema::table() block for a table.
 *
 * @return list<string>
 */
function body(string $output, string $table, string $method = 'create'): array
{
    preg_match("/Schema::{$method}\\('{$table}', function \\(Blueprint \\\$table\\) \\{\\n(.*?)\\}\\);/s", $output, $matches);

    return array_map('trim', explode("\n", rtrim($matches[1])));
}

it('renders a complete schema file', function () {
    $output = render(
        new Table(
            name: 'users',
            columns: [
                new Column('id', 'id'),
                new Column('email', 'string'),
                new Column('team_id', 'unsignedBigInteger', nullable: true),
                new Column('created_at', 'timestamp', nullable: true),
                new Column('updated_at', 'timestamp', nullable: true),
            ],
            indexes: [
                new Index(IndexType::Primary, ['id'], 'primary'),
                new Index(IndexType::Unique, ['email'], 'users_email_unique'),
            ],
            foreignKeys: [
                new ForeignKey(['team_id'], 'teams', ['id'], 'users_team_id_foreign', onDelete: 'cascade'),
            ],
        ),
        new Table(
            name: 'teams',
            columns: [
                new Column('id', 'id'),
                new Column('name', 'string'),
            ],
            indexes: [
                new Index(IndexType::Primary, ['id'], 'primary'),
            ],
        ),
    );

    expect($output)->toBe(<<<'PHP'
        <?php

        /*
         * This file is auto-generated by laravel-schema-file from the current state of the database.
         * Do not edit it by hand: it is rewritten after every migration.
         *
         * It's strongly recommended that you check this file into your version control system.
         */

        use Illuminate\Database\Schema\Blueprint;
        use Illuminate\Support\Facades\Schema;

        Schema::create('teams', function (Blueprint $table) {
            $table->id();
            $table->string('name');
        });

        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('email')->unique();
            $table->unsignedBigInteger('team_id')->nullable();
            $table->timestamps();
        });

        Schema::table('users', function (Blueprint $table) {
            $table->foreign('team_id')->references('id')->on('teams')->onDelete('cascade');
        });

        PHP);
});

it('renders only the header and imports for an empty schema', function () {
    expect(render())
        ->toStartWith("<?php\n\n/*\n * This file is auto-generated")
        ->toEndWith("use Illuminate\\Support\\Facades\\Schema;\n")
        ->not->toContain('Schema::create');
});

it('renders the same output whatever order the schema is passed in', function () {
    $indexes = [
        new Index(IndexType::Index, ['b', 'a'], 'things_b_a_index'),
        new Index(IndexType::Unique, ['a', 'b'], 'things_a_b_unique'),
        new Index(IndexType::Index, ['a', 'b'], 'things_a_b_index'),
    ];
    $foreignKeys = [
        new ForeignKey(['b'], 'others', ['id']),
        new ForeignKey(['a'], 'others', ['id']),
    ];
    $columns = [new Column('a', 'integer'), new Column('b', 'integer')];

    $things = new Table('things', $columns, $indexes, $foreignKeys);
    $shuffled = new Table('things', $columns, array_reverse($indexes), array_reverse($foreignKeys));
    $others = new Table('others', [new Column('id', 'id')]);

    expect(render($things, $others))->toBe(render($others, $shuffled));

    expect(body(render($things), 'things'))->toBe([
        "\$table->integer('a');",
        "\$table->integer('b');",
        '',
        "\$table->unique(['a', 'b']);",
        "\$table->index(['a', 'b']);",
        "\$table->index(['b', 'a']);",
    ]);
});

describe('columns', function () {
    it('keeps columns in database order', function () {
        $output = render(new Table('t', [new Column('z', 'string'), new Column('a', 'string')]));

        expect(body($output, 't'))->toBe(["\$table->string('z');", "\$table->string('a');"]);
    });

    it('passes extra arguments to the column method', function () {
        $output = render(new Table('t', [
            new Column('code', 'string', [32]),
            new Column('price', 'decimal', [8, 2]),
            new Column('status', 'enum', [['draft', 'published']]),
        ]));

        expect(body($output, 't'))->toBe([
            "\$table->string('code', 32);",
            "\$table->decimal('price', 8, 2);",
            "\$table->enum('status', ['draft', 'published']);",
        ]);
    });

    it('renders modifiers in a fixed order', function () {
        $output = render(new Table('t', [
            new Column('votes', 'integer', nullable: true, unsigned: true, default: 0, comment: 'Vote count'),
            new Column('legacy_id', 'integer', unsigned: true, autoIncrement: true),
        ]));

        expect(body($output, 't'))->toBe([
            "\$table->integer('votes')->unsigned()->nullable()->default(0)->comment('Vote count');",
            "\$table->integer('legacy_id')->unsigned()->autoIncrement();",
        ]);
    });

    it('renders defaults of every supported type', function () {
        $output = render(new Table('t', [
            new Column('a', 'string', default: 'draft'),
            new Column('b', 'string', default: ''),
            new Column('c', 'integer', default: 0),
            new Column('d', 'float', default: 1.5),
            new Column('e', 'boolean', default: false),
            new Column('f', 'boolean', default: true),
        ]));

        expect(body($output, 't'))->toBe([
            "\$table->string('a')->default('draft');",
            "\$table->string('b')->default('');",
            "\$table->integer('c')->default(0);",
            "\$table->float('d')->default(1.5);",
            "\$table->boolean('e')->default(false);",
            "\$table->boolean('f')->default(true);",
        ]);
    });

    it('renders raw SQL defaults with DB::raw and imports the facade', function () {
        $output = render(new Table('t', [
            new Column('seen_at', 'timestamp', default: new Expression('CURRENT_TIMESTAMP')),
        ]));

        expect(body($output, 't'))->toBe(["\$table->timestamp('seen_at')->default(DB::raw('CURRENT_TIMESTAMP'));"])
            ->and($output)->toContain(
                "use Illuminate\\Database\\Schema\\Blueprint;\nuse Illuminate\\Support\\Facades\\DB;\nuse Illuminate\\Support\\Facades\\Schema;\n"
            );
    });

    it('does not import the DB facade when no raw default is used', function () {
        $renderer = new SchemaRenderer;

        $renderer->render([new Table('t', [new Column('a', 'timestamp', default: new Expression('NOW()'))])]);

        expect($renderer->render([new Table('t', [new Column('a', 'string')])]))->not->toContain('Facades\\DB');
    });

    it('escapes quotes and backslashes in strings', function () {
        $output = render(new Table('t', [
            new Column('a', 'string', default: "it's", comment: 'App\\Models'),
        ]));

        expect(body($output, 't'))->toBe(["\$table->string('a')->default('it\\'s')->comment('App\\\\Models');"]);
    });

    it('renders id() without arguments only for a column named id', function () {
        $output = render(new Table('t', [new Column('id', 'id')]), new Table('u', [new Column('uid', 'id')]));

        expect(body($output, 't'))->toBe(['$table->id();'])
            ->and(body($output, 'u'))->toBe(["\$table->id('uid');"]);
    });
});

describe('timestamps', function () {
    it('folds created_at and updated_at into timestamps()', function () {
        $output = render(new Table('t', [
            new Column('created_at', 'timestamp', [6], nullable: true),
            new Column('updated_at', 'timestamp', [6], nullable: true),
        ]));

        expect(body($output, 't'))->toBe(['$table->timestamps(6);']);
    });

    it('does not fold when the pair differs from what timestamps() creates', function (Column $createdAt, Column $updatedAt) {
        $output = render(new Table('t', [$createdAt, $updatedAt]));

        expect(body($output, 't'))->toHaveCount(2)->not->toContain('$table->timestamps();');
    })->with([
        'not nullable' => [
            new Column('created_at', 'timestamp'),
            new Column('updated_at', 'timestamp', nullable: true),
        ],
        'different type' => [
            new Column('created_at', 'dateTime', nullable: true),
            new Column('updated_at', 'timestamp', nullable: true),
        ],
        'different precision' => [
            new Column('created_at', 'timestamp', [3], nullable: true),
            new Column('updated_at', 'timestamp', [6], nullable: true),
        ],
        'has a default' => [
            new Column('created_at', 'timestamp', nullable: true, default: new Expression('CURRENT_TIMESTAMP')),
            new Column('updated_at', 'timestamp', nullable: true),
        ],
        'wrong order' => [
            new Column('updated_at', 'timestamp', nullable: true),
            new Column('created_at', 'timestamp', nullable: true),
        ],
    ]);

    it('does not fold when the columns are not adjacent', function () {
        $output = render(new Table('t', [
            new Column('created_at', 'timestamp', nullable: true),
            new Column('name', 'string'),
            new Column('updated_at', 'timestamp', nullable: true),
        ]));

        expect(body($output, 't'))->toHaveCount(3);
    });

    it('does not fold when one of the columns carries an inline index', function () {
        $output = render(new Table(
            't',
            [
                new Column('created_at', 'timestamp', nullable: true),
                new Column('updated_at', 'timestamp', nullable: true),
            ],
            [new Index(IndexType::Index, ['created_at'], 't_created_at_index')],
        ));

        expect(body($output, 't'))->toBe([
            "\$table->timestamp('created_at')->nullable()->index();",
            "\$table->timestamp('updated_at')->nullable();",
        ]);
    });
});

describe('indexes', function () {
    it('chains a single-column index with a default name onto its column', function () {
        $output = render(new Table(
            'users',
            [new Column('email', 'string'), new Column('age', 'integer'), new Column('bio', 'text')],
            [
                new Index(IndexType::Unique, ['email'], 'users_email_unique'),
                new Index(IndexType::Index, ['age']),
                new Index(IndexType::FullText, ['bio'], 'users_bio_fulltext'),
            ],
        ));

        expect(body($output, 'users'))->toBe([
            "\$table->string('email')->unique();",
            "\$table->integer('age')->index();",
            "\$table->text('bio')->fullText();",
        ]);
    });

    it('gives a custom-named index its own line with the name', function () {
        $output = render(new Table(
            'users',
            [new Column('email', 'string')],
            [new Index(IndexType::Unique, ['email'], 'uniq_email')],
        ));

        expect(body($output, 'users'))->toBe([
            "\$table->string('email');",
            '',
            "\$table->unique('email', 'uniq_email');",
        ]);
    });

    it('gives composite indexes their own line, naming only non-default names', function () {
        $output = render(new Table(
            'posts',
            [new Column('user_id', 'integer'), new Column('slug', 'string')],
            [
                new Index(IndexType::Unique, ['user_id', 'slug'], 'posts_user_id_slug_unique'),
                new Index(IndexType::Index, ['slug', 'user_id'], 'slug_lookup'),
            ],
        ));

        expect(array_slice(body($output, 'posts'), 3))->toBe([
            "\$table->unique(['user_id', 'slug']);",
            "\$table->index(['slug', 'user_id'], 'slug_lookup');",
        ]);
    });

    it('chains only one index per column', function () {
        $output = render(new Table(
            'users',
            [new Column('email', 'string')],
            [
                new Index(IndexType::Index, ['email'], 'users_email_index'),
                new Index(IndexType::Unique, ['email'], 'users_email_unique'),
            ],
        ));

        expect(body($output, 'users'))->toBe([
            "\$table->string('email')->unique();",
            '',
            "\$table->index('email');",
        ]);
    });

    it('omits the primary key of an auto-incrementing column', function () {
        $output = render(
            new Table('a', [new Column('id', 'id')], [new Index(IndexType::Primary, ['id'], 'primary')]),
            new Table('b', [new Column('n', 'integer', autoIncrement: true)], [new Index(IndexType::Primary, ['n'], 'b_pkey')]),
        );

        expect(body($output, 'a'))->toBe(['$table->id();'])
            ->and(body($output, 'b'))->toBe(["\$table->integer('n')->autoIncrement();"]);
    });

    it('chains a single-column primary key whatever the database calls it', function () {
        $output = render(new Table(
            'cache',
            [new Column('key', 'string')],
            [new Index(IndexType::Primary, ['key'], 'cache_pkey')],
        ));

        expect(body($output, 'cache'))->toBe(["\$table->string('key')->primary();"]);
    });

    it('renders a composite primary key on its own line without a name', function () {
        $output = render(new Table(
            'role_user',
            [new Column('role_id', 'integer'), new Column('user_id', 'integer')],
            [new Index(IndexType::Primary, ['role_id', 'user_id'], 'PRIMARY')],
        ));

        expect(array_slice(body($output, 'role_user'), 2))->toBe(['', "\$table->primary(['role_id', 'user_id']);"]);
    });
});

describe('foreign keys', function () {
    it('renders them after every table has been created', function () {
        $output = render(
            new Table('a_posts', [new Column('user_id', 'integer')], foreignKeys: [new ForeignKey(['user_id'], 'z_users', ['id'])]),
            new Table('z_users', [new Column('id', 'id')]),
        );

        expect(strpos($output, "Schema::table('a_posts'"))->toBeGreaterThan(strpos($output, "Schema::create('z_users'"))
            ->and(body($output, 'a_posts', 'table'))->toBe([
                "\$table->foreign('user_id')->references('id')->on('z_users');",
            ]);
    });

    it('renders actions, custom names and composite keys', function () {
        $output = render(new Table('posts', [], [], [
            new ForeignKey(['user_id'], 'users', ['id'], 'posts_user_id_foreign', onUpdate: 'cascade', onDelete: 'set null'),
            new ForeignKey(['author_id'], 'users', ['id'], 'fk_author'),
            new ForeignKey(['tenant_id', 'team_id'], 'teams', ['tenant_id', 'id']),
        ]));

        expect(body($output, 'posts', 'table'))->toBe([
            "\$table->foreign('author_id', 'fk_author')->references('id')->on('users');",
            "\$table->foreign(['tenant_id', 'team_id'])->references(['tenant_id', 'id'])->on('teams');",
            "\$table->foreign('user_id')->references('id')->on('users')->onUpdate('cascade')->onDelete('set null');",
        ]);
    });
});
