<?php

declare(strict_types=1);

namespace GGermanBoldyrev\SchemaFile\Renderer;

use GGermanBoldyrev\SchemaFile\Schema\Column;
use GGermanBoldyrev\SchemaFile\Schema\Expression;
use GGermanBoldyrev\SchemaFile\Schema\ForeignKey;
use GGermanBoldyrev\SchemaFile\Schema\Index;
use GGermanBoldyrev\SchemaFile\Schema\IndexType;
use GGermanBoldyrev\SchemaFile\Schema\Table;

/**
 * Turns a database schema, described as Table objects, into the PHP source of the schema file.
 *
 * The renderer knows nothing about databases: it receives columns that already name
 * their Blueprint method and only decides how the file reads — the order of tables,
 * which indexes are chained onto their column, what collapses into id() or timestamps(),
 * and where foreign keys go.
 *
 * It holds no state, so one instance can render any number of schemas, and the same
 * schema always produces byte-for-byte the same output.
 */
final readonly class SchemaRenderer
{
    private const string INDENT = '    ';

    private const string HEADER = <<<'PHP'
        /*
         * This file is auto-generated by laravel-schema-file from the current state of the database.
         * Do not edit it by hand: it is rewritten after every migration.
         *
         * It's strongly recommended that you check this file into your version control system.
         */
        PHP;

    /**
     * Render the contents of the schema file.
     *
     * The output depends only on the schema itself, never on the order in
     * which tables, indexes or foreign keys were passed in.
     *
     * @param  list<Table>  $tables
     */
    public function render(array $tables): string
    {
        usort($tables, fn (Table $a, Table $b) => strcmp($a->name, $b->name));

        $blocks = array_map($this->renderCreate(...), $tables);

        // Foreign keys go last so that every referenced table already exists.
        foreach ($tables as $table) {
            if ($table->foreignKeys !== []) {
                $blocks[] = $this->renderForeignKeys($table);
            }
        }

        $imports = ['use Illuminate\Database\Schema\Blueprint;'];

        if ($this->usesRawExpressions($tables)) {
            $imports[] = 'use Illuminate\Support\Facades\DB;';
        }

        $imports[] = 'use Illuminate\Support\Facades\Schema;';

        return implode("\n\n", ['<?php', self::HEADER, implode("\n", $imports), ...$blocks])."\n";
    }

    private function renderCreate(Table $table): string
    {
        [$inline, $standalone] = $this->splitIndexes($table);

        $lines = [];
        $columns = $table->columns;

        for ($i = 0; $i < count($columns); $i++) {
            $column = $columns[$i];
            $next = $columns[$i + 1] ?? null;

            if ($next !== null && $this->areTimestamps($column, $next, $inline)) {
                $lines[] = '$table->timestamps('.$this->exportList($column->arguments).');';
                $i++;

                continue;
            }

            $lines[] = $this->renderColumn($column, $inline[$column->name] ?? null);
        }

        if ($lines !== [] && $standalone !== []) {
            $lines[] = '';
        }

        foreach ($standalone as $index) {
            $lines[] = $this->renderIndex($table, $index);
        }

        return $this->wrap('create', $table, $lines);
    }

    private function renderForeignKeys(Table $table): string
    {
        $foreignKeys = $table->foreignKeys;

        usort($foreignKeys, fn (ForeignKey $a, ForeignKey $b) => [implode(',', $a->columns), $a->name]
            <=> [implode(',', $b->columns), $b->name]);

        return $this->wrap('table', $table, array_map(
            fn (ForeignKey $foreignKey) => $this->renderForeignKey($table, $foreignKey),
            $foreignKeys,
        ));
    }

    /**
     * @param  list<string>  $lines
     */
    private function wrap(string $method, Table $table, array $lines): string
    {
        $body = implode('', array_map(
            fn (string $line) => $line === '' ? "\n" : self::INDENT.$line."\n",
            $lines,
        ));

        return "Schema::{$method}({$this->export($table->name)}, function (Blueprint \$table) {\n{$body}});";
    }

    private function renderColumn(Column $column, ?Index $inlineIndex): string
    {
        $isId = $column->method === 'id';

        $arguments = $isId && $column->name === 'id'
            ? []
            : [$column->name, ...$column->arguments];

        $line = "\$table->{$column->method}(".$this->exportList($arguments).')';

        if ($column->unsigned && ! $isId) {
            $line .= '->unsigned()';
        }

        if ($column->autoIncrement && ! $isId) {
            $line .= '->autoIncrement()';
        }

        if ($column->virtualAs !== null) {
            $line .= '->virtualAs('.$this->export($column->virtualAs).')';
        }

        if ($column->storedAs !== null) {
            $line .= '->storedAs('.$this->export($column->storedAs).')';
        }

        $line .= $this->renderNullability($column);

        if ($column->default !== null) {
            $line .= '->default('.$this->export($column->default).')';
        }

        if ($column->comment !== null) {
            $line .= '->comment('.$this->export($column->comment).')';
        }

        if ($inlineIndex !== null) {
            $line .= "->{$inlineIndex->type->method()}()";
        }

        return $line.';';
    }

    /**
     * An ordinary column is NOT NULL unless marked nullable; a generated one is
     * nullable unless marked otherwise. Only the departure from that is written.
     */
    private function renderNullability(Column $column): string
    {
        if ($column->isGenerated()) {
            return $column->nullable ? '' : '->nullable(false)';
        }

        return $column->nullable ? '->nullable()' : '';
    }

    private function renderIndex(Table $table, Index $index): string
    {
        $arguments = [$this->columnsArgument($index->columns)];

        if ($index->type !== IndexType::Primary && ! $this->hasDefaultName($table, $index)) {
            $arguments[] = $index->name;
        }

        return "\$table->{$index->type->method()}(".$this->exportList($arguments).');';
    }

    private function renderForeignKey(Table $table, ForeignKey $foreignKey): string
    {
        $arguments = [$this->columnsArgument($foreignKey->columns)];

        if ($foreignKey->name !== null && $foreignKey->name !== $this->defaultName($table, $foreignKey->columns, 'foreign')) {
            $arguments[] = $foreignKey->name;
        }

        $line = '$table->foreign('.$this->exportList($arguments).')'
            .'->references('.$this->export($this->columnsArgument($foreignKey->foreignColumns)).')'
            .'->on('.$this->export($foreignKey->foreignTable).')';

        if ($foreignKey->onUpdate !== null) {
            $line .= '->onUpdate('.$this->export($foreignKey->onUpdate).')';
        }

        if ($foreignKey->onDelete !== null) {
            $line .= '->onDelete('.$this->export($foreignKey->onDelete).')';
        }

        return $line.';';
    }

    /**
     * Decide which indexes are chained onto their column and which get a line of their own.
     *
     * @return array{array<string, Index>, list<Index>}
     */
    private function splitIndexes(Table $table): array
    {
        $columns = [];

        foreach ($table->columns as $column) {
            $columns[$column->name] = $column;
        }

        $order = array_flip(array_column(IndexType::cases(), 'value'));
        $indexes = $table->indexes;

        usort($indexes, fn (Index $a, Index $b) => [$order[$a->type->value], implode(',', $a->columns), $a->name]
            <=> [$order[$b->type->value], implode(',', $b->columns), $b->name]);

        $inline = [];
        $standalone = [];

        foreach ($indexes as $index) {
            $column = count($index->columns) === 1 ? ($columns[$index->columns[0]] ?? null) : null;

            if ($column !== null) {
                $isPrimary = $index->type === IndexType::Primary;

                // An auto-incrementing column is already the primary key.
                if ($isPrimary && ($column->method === 'id' || $column->autoIncrement)) {
                    continue;
                }

                if (! isset($inline[$column->name]) && ($isPrimary || $this->hasDefaultName($table, $index))) {
                    $inline[$column->name] = $index;

                    continue;
                }
            }

            $standalone[] = $index;
        }

        return [$inline, $standalone];
    }

    /**
     * Whether two adjacent columns are exactly what $table->timestamps() creates.
     *
     * @param  array<string, Index>  $inline
     */
    private function areTimestamps(Column $createdAt, Column $updatedAt, array $inline): bool
    {
        if ($createdAt->name !== 'created_at' || $updatedAt->name !== 'updated_at') {
            return false;
        }

        if ($createdAt->arguments !== $updatedAt->arguments) {
            return false;
        }

        foreach ([$createdAt, $updatedAt] as $column) {
            if ($column->method !== 'timestamp'
                || ! $column->nullable
                || $column->unsigned
                || $column->default !== null
                || $column->comment !== null
                || $column->isGenerated()
                || isset($inline[$column->name])) {
                return false;
            }
        }

        return true;
    }

    private function hasDefaultName(Table $table, Index $index): bool
    {
        return $index->name === null
            || $index->name === $this->defaultName($table, $index->columns, $index->type->suffix());
    }

    /**
     * The name Laravel gives an index or foreign key when none is specified.
     *
     * @param  list<string>  $columns
     */
    private function defaultName(Table $table, array $columns, string $suffix): string
    {
        $name = strtolower($table->name.'_'.implode('_', $columns).'_'.$suffix);

        return str_replace(['-', '.'], '_', $name);
    }

    /**
     * Whether any column default is raw SQL, which the file writes as DB::raw().
     *
     * @param  list<Table>  $tables
     */
    private function usesRawExpressions(array $tables): bool
    {
        foreach ($tables as $table) {
            foreach ($table->columns as $column) {
                if ($column->default instanceof Expression) {
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * @param  list<string>  $columns
     * @return string|list<string>
     */
    private function columnsArgument(array $columns): string|array
    {
        return count($columns) === 1 ? $columns[0] : $columns;
    }

    /**
     * @param  list<mixed>  $values
     */
    private function exportList(array $values): string
    {
        return implode(', ', array_map($this->export(...), $values));
    }

    private function export(mixed $value): string
    {
        return match (true) {
            $value instanceof Expression => 'DB::raw('.$this->export($value->sql).')',
            is_string($value) => "'".addcslashes($value, "'\\")."'",
            is_bool($value) => $value ? 'true' : 'false',
            is_array($value) => '['.$this->exportList($value).']',
            default => var_export($value, true),
        };
    }
}
